export const FETCH_POST_CATEGORIES = 'FETCH_POST_CATEGORIES'
export const FETCH_POST_CATEGORIES_SUCCEED = 'FETCH_POST_CATEGORIES_SUCCEED'
export const FETCH_POST_CATEGORIES_FAILED = 'FETCH_POST_CATEGORIES_FAILED'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_SUCCEED = 'CREATE_POST_SUCCEED'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'
