export const FETCH_POST_CATEGORIES = 'FETCH_POST_CATEGORIES'
export const FETCH_POST_CATEGORIES_SUCCEED = 'FETCH_POST_CATEGORIES_SUCCEED'
export const FETCH_POST_CATEGORIES_FAILED = 'FETCH_POST_CATEGORIES_FAILED'
