export const TEST_REQUEST = 'TEST_REQUEST'
export const TEST_SUCCEED = 'TEST_SUCCEED'
export const TEST_FAILED = 'TEST_FAILED'

export const GET_RECENT_POSTS = 'GET_RECENT_POSTS'
export const GET_RECENT_POSTS_SUCCEED = 'GET_RECENT_POSTS_SUCCEED'
export const GET_RECENT_POSTS_FAILED = 'GET_RECENT_POSTS_FAILED'