export const FETCH_BLOG_LIST = 'FETCH_BLOG_LIST'
export const FETCH_BLOG_LIST_SUCCEED = 'FETCH_BLOG_LIST_SUCCEED'
export const FETCH_BLOG_LIST_FAILED = 'FETCH_BLOG_LIST_FAILED'

export const SET_BLOG_END_PAGINATION = 'SET_BLOG_END_PAGINATION'