export const FETCH_BLOG_DETAIL = 'FETCH_BLOG_DETAIL'
export const FETCH_BLOG_DETAIL_SUCCEED = 'FETCH_BLOG_DETAIL_SUCCEED'
export const FETCH_BLOG_DETAIL_FAILED = 'FETCH_BLOG_DETAIL_FAILED'

export const CREATE_BLOG_POST_COMMENT = 'CREATE_BLOG_POST_COMMENT'
export const CREATE_BLOG_POST_COMMENT_SUCCEED = 'CREATE_BLOG_POST_COMMENT_SUCCEED'
export const CREATE_BLOG_POST_COMMENT_FAILED = 'CREATE_BLOG_POST_COMMENT_FAILED'

export const CREATE_POST_COMMENT_REPLY = 'CREATE_POST_COMMENT_REPLY'
export const CREATE_POST_COMMENT_REPLY_SUCCEED = 'CREATE_POST_COMMENT_REPLY_SUCCEED'
export const CREATE_POST_COMMENT_REPLY_FAILED = 'CREATE_POST_COMMENT_REPLY_FAILED'