export const LOGIN = 'LOGIN'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION'
export const CHECK_AUTHENTICATION_SUCCEED = 'CHECK_AUTHENTICATION_SUCCEED'
export const CHECK_AUTHENTICATION_FAILED = 'CHECK_AUTHENTICATION_FAILED'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCEED = 'FETCH_USER_SUCCEED'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'